### ISSUE TITLE
GPLv2 license clarification

### ISSUE THREAD

**Issue by blagerweij** [awslabs/aws-mysql-jdbc#178]
Please clarify the GPLv2 License: are we allowed to use this JDBC driver in commercial software that we run on Amazon servers? Additionally, when doing so, are we required to open-source our commercial software ?

I ask this question since there is a lot of confusion on the GPLv2 license change with the MySQL driver, and I was somewhat suprised to see the same license being used here. Many license scanning tools (and legal people) are red-flagging any library which uses the GPLv2 license.

Any clarification on this would be greatly appreciated

**Comment by hsuamz** [comment]
Hello @blagerweij,

A very common deployment scenario is to use the JDBC driver in your commercial software that you run in your AWS account without having to open-source your software. We can’t provide legal advice, though, so you should discuss the license with your legal counsel if you have further questions, especially any that require getting into specifics about how you’re using the driver with your software.

Thanks,

Matthew
