### ISSUE TITLE
Support AWS SDK for Java 2.x for AWS IAM Database Authentication

### ISSUE THREAD

**Issue by AndreasHuber-CH** [awslabs/aws-mysql-jdbc#184]
- [ ] bug report
- [x] feature request
    
Using AWS IAM Database Authentication requires currently the following maven dependency:
```
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-rds</artifactId>
</dependency>
```

I'd like to use it based on the newer AWS SDK for Java 2.x:
```
<dependency>
	<groupId>software.amazon.awssdk</groupId>
	<artifactId>rds</artifactId>
</dependency>
```

While it is possible to mix the old and new java SDK in the same application, the older sdk does not have the **sso** library that has been added to the new **awssdk**.
Because of that limitation it is currently not possible to combine SSO and AWS IAM Database Authentication using this driver. In my case this means I cannot use AWS IAM Database Authentication in my development environment where I use SSO to manage AWS credentials.

Would you be interested in adding this feature?

**Comment by maciejwalkowiak** [comment]
Looks like this has been fixed in https://github.com/awslabs/aws-mysql-jdbc/commit/5b937fc9f6b9832a5037840001bb130606ee8761

**Comment by jaecktec** [comment]
when will it be available? 1.0.0 still requires the sdkv1 dependency

**Comment by maksimsc** [comment]
Any plans to release it?

**Comment by sergiyvamz** [comment]
Hello @maksimsc 

A new version of the driver has been released.
https://github.com/awslabs/aws-mysql-jdbc/releases/tag/1.1.0
