### ISSUE TITLE
Can I use load balancing to reader instance for read-only transactions, as the mariadb connector supports?

### ISSUE THREAD

**Issue by 21kyu** [awslabs/aws-mysql-jdbc#185]
**Describe the issue**
Can I use load balancing to reader instance for _read-only_ transactions, as the mariadb connector supports?
[Primary/replica connection selection](https://mariadb.com/kb/en/failover-and-high-availability-with-mariadb-connector-j/#primaryreplica-connection-selection)

I tried to load balance by implementing `AbstractRoutingDataSource`, but it didn't seem to work.
Please let me know if there is a way to make _read-only_ transactions only processed by the reader instances.

**Driver Version?** 
software.aws.rds:aws-mysql-jdbc:1.0.0

**Java Version?**
8 or 11

**OS Version?**
amazon linux used as the worker node of eks

**MySQL Version?**
5.7.mysql_aurora.2.09.2

**To Reproduce**
Steps to reproduce the behaviour:
1. Add `implementation 'software.aws.rds:aws-mysql-jdbc:1.0.0'` to build.gradle.
2. Create 2 datasources for writer/reader. (both set the connection pool to 50)
3. Implement `AbstractRoutingDataSource` to route transactions.
4. There are 4 pods and the application runs in each pod.
5. Run some workloads.

**Expected behaviour**
Primary/replica connection selection: _read-only_ transactions must be sent to the reader instances.

**Logs**
* test-db-instance-1: Writer instance
* test-db-instance-2: Reader instance

General log of query with `@Transactional(readOnly = true)`

Timestamp | Message | Log stream name
-- | -- | --
 2022-03-29T15:45:43.648+09:00 | 2022-03-29T06:45:43.648313Z 341 Query SELECT test_type FRO ... | test-db-instance-1
 2022-03-29T15:46:12.237+09:00 | 2022-03-29T06:46:12.237192Z 341 Query SELECT test_type FRO ... | test-db-instance-2
 2022-03-29T15:46:44.359+09:00 | 2022-03-29T06:46:44.359068Z 341 Query SELECT test_type FRO ... | test-db-instance-1
 2022-03-29T15:47:01.764+09:00 | 2022-03-29T06:47:01.764842Z 341 Query SELECT test_type FRO ... | test-db-instance-1
... | ... | ...

**Comment by sergiyvamz** [comment]
Hello @21kyu,

Thank you for giving the AWS JDBC Driver for MySQL a try! 

It seems that logic you're trying to achieve is supported. You may consider to use `jdbc:mysql:replication://` protocol and do necessary adjustments to your configuration and to your application code. More details are available at: https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-source-replica-replication-connection.html.

Would you mind to provide more details about the context key that you use for your implementation of `AbstractRoutingDataSource`? Does this context key change according to whether read or write operation is needed? Assuming the context key has a proper value for both read and write cases, the rest of the logic relies on data sources. You may also need to make sure that replica data source is configured with replication protocol and a proper list of nodes. 

If you use an Aurora MySQL cluster, you may consider to use cluster reader endpoint to connect to a random replica node.
