### ISSUE TITLE
aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (77,210 > 65,535)

### ISSUE THREAD

**Issue by robisrob** [awslabs/aws-mysql-jdbc#191]
**Describe the issue**
The _max_allowed_packet_ on the mysql server is configured at 200000. On our client side, we have not set the max_allowed_packet size. 

So queries that return a result that is smaller than 200000, don't give problems in general. However on rare occasions we do get the following error:

`org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL [SELECT notes FROM person WHERE id = ?; Packet for query is too large (77,210 > 65,535). You can change this value on the server by setting the 'max_allowed_packet' variable.; nested exception is software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (77,210 > 65,535).`

If we restart the application, the query causing the issue, works again.

**Driver Version?** 
software.aws.rds:aws-mysql-jdbc:1.0.0

**Java Version?**
18

**MySQL Version?**
8

**Comment by sergiyvamz** [comment]
Hello @robisrob,

Would you mind to provide a bit more details about your application and your MySQL database.

1. Do you use Aurora MySQL DB cluster or any other MySQL server?
2. What your connection string looks like? Does it use IP address, domain name, localhost?
3. Do you experience the same issue when you use [MySQL Connector/J driver](https://github.com/mysql/mysql-connector-j)?
4. Do you see any relations between your issue and DB cluster failover events? 

Thank you!

**Comment by robisrob** [comment]
1. We use Aurora
2. domain name
3. We used the org.mariadb.jdbc.Driver and didn't had this problem then
4. No

When are now setting the max_allowed_packet on our client side explicitly and don't have the problem anymore

**Comment by abrahammj** [comment]
We got the same issue with a server configured with 128MB _max_allowed_packet_ setting; We have a LONGBLOB column and whenever large binary data is inserted/read, this exception is thrown. The problem can be avoided using _maxAllowedPacket_ jdbc URL parameter, but  we would have preferred the driver to respect the server settings.

**Comment by Howu48** [comment]
@sergiyvamz Same issue here.
1. Do you use Aurora MySQL DB cluster or any other MySQL server?
 : Aurora
2. What your connection string looks like? Does it use IP address, domain name, localhost?
 : Cluster Endpoint
3. Do you experience the same issue when you use [MySQL Connector/J driver](https://github.com/mysql/mysql-connector-j)?
 : No
4. Do you see any relations between your issue and DB cluster failover events?
 : No

**Comment by matheusrossato** [comment]
@sergiyvamz same issue here with AWS Aurora MySQL Driver not respecting the server settings. To solve this, we needed to add also max_allowed_packet in the connectionString to correspond to the server setting to something like this: 

jdbc\\:mysql:aws\\://${DB_URL}/${DB_NAME}?&failOverReadOnly\\=false&maxAllowedPacket\\=4194304
<img width="558" alt="Screen Shot 2022-05-10 at 10 27 48" src="https://user-images.githubusercontent.com/1878439/167639712-d57f4962-db03-4236-9f50-bb9916980833.png">

Do you use Aurora MySQL DB cluster or any other MySQL server?
: Aurora only
What your connection string looks like? Does it use IP address, domain name, localhost?
: DNS to Cluster Endpoint
Do you experience the same issue when you use [MySQL Connector/J driver](https://github.com/mysql/mysql-connector-j)?
: No, works fine;
Do you see any relations between your issue and DB cluster failover events?
: No relation.


Part of the error message we faced before adding the parameter into the connection string:

> message: "Operation failed : Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.4.payara-p2): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (203,353 > 65,535). You can change this value on the server by setting the 'max_allowed_packet' variable. Error Code: 0 Call: SELECT...

**Comment by karenc-bq** [comment]
Hi all, we understand this issue is causing inconveniences in your workflows and we are currently working on a fix: #211. 
We will update you when we have a release. We appreciate your patience.

**Comment by hsuamz** [comment]
The fix for this issue has been merged in. We will be closing this issue and we will be providing an updated release soon. Please reopen this issue if it persists.

Thanks.
