### ISSUE TITLE
java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown

### ISSUE THREAD

**Issue by donggak** [awslabs/aws-mysql-jdbc#203]
**Describe the issue**
A clear and concise description of what the issue is.

**Driver Version?** 
aws-mysql-jdbc (version 1.0.0)

**Java Version?**

**OS Version?**

**MySQL Version?**
8.0.mysql_aurora.3.01.0

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
And what actually happens

**Logs**
If possible MySQL logs surrounding the occurrence of the issue

**Comment by donggak** [comment]
--> Customer Issue
I am using aws-mysql-jdbc 1.0.0, and the above error occurs.
However, no error occurs in mariadb-java-client (version 2.3.0).
My database is using Aurora MySQL. Can I use mariadb-java-client (version 2.3.0) when considering Aurora Mysql upgrade or failover?

**Comment by hsuamz** [comment]
Hello @donggak,

Thanks for reaching out. Have you read through this section in our README? For reference: https://github.com/awslabs/aws-mysql-jdbc#08007---transaction-resolution-unknown.

It's not clear what's happening in the attached logs. If you are following the above guidelines and the issue still persists, could you share some more information in the query workflow that you are trying to execute?

Thanks,

Matthew

**Comment by donggak** [comment]
Hello @Matthew,
Thank you for checking
I'll take a closer look at reference you mentioned. and I'll update it if the issue persist.

Thanks,

**Comment by davecramer** [comment]
@donggak is this still an issue ?

**Comment by donggak** [comment]
this issue has been resolved
