### ISSUE TITLE
Why this project source code license use GPL v2 not Apache 2.0

### ISSUE THREAD

**Issue by LuckyDogg** [awslabs/aws-mysql-jdbc#216]
**Describe the issue**
I found this driver by this blog(https://awslabs.github.io/aws-mysql-jdbc/)

I want to use this driver to improve the robustness of our application to failover, so I paid attention to this project

Then I am confused about the source code license, I use AWS aurora Cluster , I think most users who want to use this driver also use Aurora Cluster 

This license is not friendly to commercial application,is it appropriate which mainly used by users who use Aurora Cluster (Commercial Cloud Paas )

I respect the work of the open source community, but I want to know the answer about this question. 
The license will affect whether I can use the driver

**Driver Version?** 
1.0.0
**Java Version?**

**OS Version?**

**MySQL Version?**
Aurora
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
And what actually happens

**Logs**
If possible MySQL logs surrounding the occurrence of the issue

**Comment by hsuamz** [comment]
Hello @LuckyDogg,

This driver is based on the [MySQL Connector/J driver](https://github.com/mysql/mysql-connector-j). The [license](https://github.com/mysql/mysql-connector-j/blob/release/8.0/LICENSE) of the MySQL Connector/J driver is GPL-2.0. A very common deployment scenario is to use the JDBC driver in commercial software running in an AWS account. We can’t provide legal advice, though, so you should discuss the license with your legal counsel if you have further questions, especially any that require getting into specifics about how you’re using the driver with your software.

Thanks,

Matthew
