### ISSUE TITLE
DBeaver can not select schema

### ISSUE THREAD

**Issue by tomchiverton** [awslabs/aws-mysql-jdbc#261]
### Describe the bug

Unable to choose an available schema once connected

### Expected Behavior

Drop down closes, selecting the correct schema

### Current Behavior

Drop down closes, but value in tool bar remains "N/A"

Queries entered need to fully specify the schema.tablename or use "use schema".

### Reproduction Steps

Set up new driver as per the README (separate MR opened to correct the URL template ; awslabs/aws-mysql-jdbc#260)

Create new connection using new driver

Open the new connection as SQL Console

Pick a schema from the drop down list in toolbar, next to where it lists the connection name

### Additional Information/Context

DBeaver 22.1.5

### The AWS JDBC Driver for MySQL version used

1.1.0

### JDK version used

openjdk 11.0.12 2021-07-20

### Operating System and version

Ubuntu 20.04 LTS

**Comment by tomchiverton** [comment]
Works as expected using the default MySQL driver. Doesn't seem to be a setting at fault from what I can see

**Comment by sergiyvamz** [comment]
Hello @tomchiverton 

Thank you for raising the issue. We understand this issue is causing inconveniences in your workflows. We'll be investigating this issue and will update you when we have a release. We appreciate your patience.

**Comment by sergiyvamz** [comment]
Hello @tomchiverton 

According to DBeaver documentation, you can specify custom queries for a driver to facilitate some UI features like changing current schema. You can configure them at `Driver Manager`, open `AWS JDBC Driver for MySQL` settings, switch to `Advanced parameters`, and edit the following queries:

```
Get active database: select database()
Set active database: use ?
```
![image](https://user-images.githubusercontent.com/75754709/186784793-ba30b93f-c96d-4abf-bbe0-97b5b769bf50.png)

I hope this solution solve the issue!

**Comment by tomchiverton** [comment]
Yup, pull for updating the docs on it's way.
