### ISSUE TITLE
Plugins package names in connectionPluginFactories property of connectionUrl

### ISSUE THREAD

**Issue by abedali** [awslabs/aws-mysql-jdbc#293]
### Describe the issue

I'm using 
implementation group: 'software.aws.rds', name: 'aws-mysql-jdbc', version: **'1.1.1'**

Its an issue in 1.1.0 version of the driver as well.

README recommends following plugin factories with their package names as 'com.mysql.cj.jdbc.ha.plugins'
**com.mysql.cj.jdbc.ha.plugins**.failover.FailoverConnectionPluginFactory, **com.mysql.cj.jdbc.ha.plugins**.NodeMonitoringConnectionPluginFactory
**com.mysql.cj.jdbc.ha.plugins**.AWSSecretsManagerPluginFactory

But when I use them, I get following error during application start
**Unable to load connection plugin factory** 'com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPluginFactory
**Unable to load connection plugin factory** 'com.mysql.cj.jdbc.ha.plugins.NodeMonitoringConnectionPluginFactory
**Unable to load connection plugin factory** 'com.mysql.cj.jdbc.ha.plugins.AWSSecretsManagerPluginFactory

To make my application work, I used '**software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins**.' package
connectionPluginFactories=
**software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins**.failover.FailoverConnectionPluginFactory,
**software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins**.NodeMonitoringConnectionPluginFactory,
**software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins**.AWSSecretsManagerPluginFactory

Can you please recommend the right package names for plugins and update README accordingly?
This is very much needed for my project documentation.

### Links

(https://github.com/awslabs/aws-mysql-jdbc/#readme)

**Comment by sergiyvamz** [comment]
Hi @abedali 

Thank you for raising the issue! Documentation has been updated.

**Comment by abedali** [comment]
thank you
