### ISSUE TITLE
Make it AZ aware

### ISSUE THREAD

**Issue by chrillux** [awslabs/aws-mysql-jdbc#300]
### Describe the feature

Sorry if this has already been addressed before. I couldn't find anything about it in the documentation so I'll ask the question here.

It would be nice if the connector was availability zone aware, meaning that the services using the connector would prefer to use a read replica that is running in the same AZ as itself,  as this would drive down the costs for data traffic.

### Use Case

I like to save money when I can.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS JDBC Driver for MySQL version used

v1.1.1

### JDK version used

17

### Operating System and version

Alpine 3.16

**Comment by hsuamz** [comment]
Thanks for reaching out. For visibility, the connector is not AZ aware. It is a feature in our backlog and we will provide an update here when we address it.

Thanks.

**Comment by davecramer** [comment]
Support for this driver will be ending July 25/2024 as per the https://github.com/awslabs/aws-mysql-jdbc/blob/main/CONTRIBUTING.md document. Any new features will be implemented in https://github.com/aws/aws-advanced-jdbc-wrapper
