### ISSUE TITLE
Distinct ClientPreparedStatement objects incorrectly have same hashCode and match with equals()

### ISSUE THREAD

**Issue by buitcj** [awslabs/aws-mysql-jdbc#308]
### Describe the bug

Distinct `ClientPreparedStatement`s sharing a `ConnectionProxy` will all use the `hashCode()` and `equals()` of the `ConnectionProxy` and therefore will all have the same hash code and be equals via the `equals()` call. 

This is a problem not only because fundamentally the objects are different so they should have different hash codes and not be equal, but also because when using the AWS Aurora MySQL driver with Hibernate 5, the `ClientPreparedStatement`s will be registered in `ResourceRegistryStandardImpl` here https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/ResourceRegistryStandardImpl.java#L87 . This code will throw an exception when the `Statement` (key) was already registered. Multiple different statements with the same `hashCode()` that are equal via the `equals()` will cause this problem.

### Expected Behavior

Multiple `ClientPreparedStatement`s using the same `ConnectionProxy` should have different hash code values and not be equal via `equals()`

### Current Behavior

Normally, Hibernate code will throw an exception when the `Statement` (key) was already registered. It detects this by seeing if the key already exists in its map. Using the AWS Aurora MySQL driver, multiple different statements with the same `hashCode()` that are equal via the `equals()` will cause a "JDBC Statement already registered" even if the `Statement`s are not the same.

### Reproduction Steps

Using the same Hibernate `Session`, call `prepareQueryStatement()` with two different `Statement`s that use different SQL queries. 

Expected: Successful registration of the two `Statement`s

Actual: First `ClientPreparedStatement` registers successfully but the second registration has an `HibernateException` thrown from `ResourceRegistryStandardImpl` with message `JDBC Statement already registered`

### Possible Solution

One possible solution is to simply not let the proxy directly execute `equals()` and `hashCode()` and instead defer to the underlying Statement.

`src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java` implements `invoke()` (https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java#L312) which will detect if the method is `equals` or `hashCode` (https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java#L296) and if so, it uses the implementation of the `ConnectionProxy` instead of the implementation of the underlying object (https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java#L267). In this case, the underlying object is the `ClientPreparedStatement`. Two different `ClientPreparedStatement` objects that share the same `ConnectionProxy` will be equal because they share the same hash code and `equals()` will evaluate to true.

### The AWS JDBC Driver for MySQL version used

1.1.1 (and 1.1.0)

### JDK version used

1.8

### Operating System and version

MacOS Monterey 12.3.1

**Comment by sergiyvamz** [comment]
Hello @buitcj 

The fix for the issue has been applied. Will you be able to test out a snapshot build [here](https://aws.oss.sonatype.org/content/repositories/snapshots/software/aws/rds/aws-mysql-jdbc/) and let us know if the issue persists?

Thank you!

**Comment by buitcj** [comment]
Appears to work - thanks @sergiyvamz! 

When should we expect 1.1.2 to be released? What is the release schedule for the driver?

**Comment by buitcj** [comment]
@sergiyvamz friendly bump! if you don't have the answer that's fine, but I just want to have a contingency plan for our own software release if we're not going to get this fix in an official version before our deadlines

**Comment by davecramer** [comment]
@buitcj we will get back to you ASAP with an answer.

**Comment by matthewh-BQ** [comment]
Hello @buitcj, we will be including an additional fix before we release an updated driver. We are planning to release 1.1.2 early next week.

Does this align with your deadlines?

Thanks,

Matthew

**Comment by hsuamz** [comment]
Hello @buitcj, we will be including an additional fix before we release an updated driver. We are planning to release 1.1.2 early next week.

Does this align with your deadlines?

Thanks,

Matthew

**Comment by jubui** [comment]
@hsuamz Yes it does. Thanks for the update

**Comment by buitcj** [comment]
@hsuamz Yes it does. Thanks for the update

**Comment by karenc-bq** [comment]
Hi @buitcj, version 1.1.2 of the driver has been released, thank you for your patience.

**Comment by jubui** [comment]
@karenc-bq @hsuamz I don't think the new 1.1.2 driver still report a SNAPSHOT version like that. 

![image](https://user-images.githubusercontent.com/55841907/205889215-d1feb755-eb18-4724-bf25-b31820e794d6.png)
