### ISSUE TITLE
DatabaseMetaData#getDriverVersion is reporting a SNAPSHOT version

### ISSUE THREAD

**Issue by buitcj** [awslabs/aws-mysql-jdbc#318]
### Describe the bug

Official v1.1.2 release of the driver should report a non-snapshot version via `DatabaseMetaData#getDriverVersion` but instead reports a snapshot version.

### Expected Behavior

Driver version should report a non snapshot version like `aws-mysql-connector-java-1.1.2`

### Current Behavior

Driver version reports a snapshot version like `aws-mysql-connector-java-1.1.2-SNAPSHOT (Revision: d85fd009cb21f60b0a9316b94b05628633e261f7)`

![image](https://user-images.githubusercontent.com/55841907/205889789-afbbe05d-a0c9-47cc-85df-f0b56bf5e4e1.png)

### Reproduction Steps

With a valid aurora mysql instance and credentials, 

```
Connection conn = DriverManager.getConnection(jdbcUrl, userName, password);
System.out.println(conn.getMetaData().getDriverVersion());
```

with a gradle build file using maven central and `implementation 'software.aws.rds:aws-mysql-jdbc:1.1.2'`

### Possible Solution

Possible problem with release process?

### The AWS JDBC Driver for MySQL version used

1.1.2

### JDK version used

1.8

### Operating System and version

MacOS Monterey 12.6.1

**Comment by hsuamz** [comment]
Thanks for the report. We'll take a look at this.

**Comment by karenc-bq** [comment]
Thank you for raising this issue, the bug has been fixed.
