### ISSUE TITLE
AWS Mysql driver does not work if Route53 entry used instead of cluster endpoint

### ISSUE THREAD

**Issue by bmariesan** [awslabs/aws-mysql-jdbc#324]
### Describe the bug

Depending on how you look at the problem, it could be a bug, limitation or documentation missing.

In some of our environments we were using Route53 records from a past database migration (RDS proxies were not available at that time). So when we switched to use the AWS Mysql driver for autoscaling, we've noticed that in all environments using Route53 records for the writer & ro endpoints, the driver reported connection failure while working correctly on all other environments.

### Expected Behavior

The standard Mysql driver allows this behaviour but it's debatable if in a cloud environment it should be preferred since Route53 records could potentially cache removed read replicas.

If we are to stick to the behaviour in the default driver, the current behaviour is unexpected behaviour.
If this is considered an antipattern, we should update the documentation to warn around potential connectivity issues if Route53 records are used

### Current Behavior

Currently if a Route53 DNS entry is used for writer and reader, we get a connectivity failure

### Reproduction Steps

CNAME  Route53 records required on top of RDS cluster endpoint (one for writer, one for reader)

### The AWS JDBC Driver for MySQL version used

1.1.2

### JDK version used

1.8 and 17

### Operating System and version

ECS Fargate

**Comment by karenc-bq** [comment]
Hi @bmariesan, thank you for raising this issue, we will investigate it.

Thank you again for your patience!

**Comment by karenc-bq** [comment]
Hi @bmariesan, we have some follow up questions:
1. Are you able to provide us with some logs ([Documentation on how to enable logging](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging))?
2. Can you please provide us with an example of how your cluster instances map to your Route53 records?

**Comment by aaronchung-bitquill** [comment]
Hi @bmariesan 

Due to lack of feedback, we will be closing this issue. 

Please re-open if this is still a problem

Thank you!
