### ISSUE TITLE
Connection leak if no connection pooling enabled

### ISSUE THREAD

**Issue by bmariesan** [awslabs/aws-mysql-jdbc#326]
### Describe the bug

We have a service where (for the moment) Hikari connection pooling is not an option. Based on metrics from issue https://github.com/awslabs/aws-mysql-jdbc/issues/196 we were expecting some degradation in performance so that we would benefit of proper read replica detection post autoscaling events & failover. 

Immediately after the release we've started receiving alerts of an increase in WRITER db connections, we assumed it was due to metadata requests by the driver to get replica information (since pooling is disabled). Throughout the day we've noticed number of open connections steadily increasing on the replica, and after autoscaling on the 2nd replica and soon a 3rd replica, so we've went up from around 100-200 connections in average, to exhausting connections on db instances of type db.r5.4xlarge.

### Expected Behavior

With connection pooling disabled, a certain degradation of performance would be expected, however connections should be closed and recycled correctly after each request finishes.

### Current Behavior

DB connections seem to be leaking, thing suggested by the huge surge in connection open on the DB replicas as well as a huge spike in the number of ECS instances usually needed for the same load (number doubled when compared to a similar day)

### Reproduction Steps

Spring Boot 2.3.12.RELEASE, Hibernate 5.6.14 and connection pooling disabled, AWS RDS 5.7.x 

### The AWS JDBC Driver for MySQL version used

1.1.2

### JDK version used

1.8

### Operating System and version

ECS Fargate

**Comment by hsuamz** [comment]
Thanks for sharing that information. We will reach out once we have started investigation.

**Comment by karenc-bq** [comment]
Hi @bmariesan, we have some follow up questions:
1. How are you monitoring the opened connections?
2. Are you able to provide us with some sample code snippets from your service so we can reproduce the behaviour?

**Comment by aaronchung-bitquill** [comment]
Hi @bmariesan

Due to lack of feedback, we will be closing this issue.

Please re-open if this is still a problem

Thank you!
