### ISSUE TITLE
AWS Aurora MySql 8.0 database - Reactive JDBC Driver support 

### ISSUE THREAD

**Issue by riruvuri** [awslabs/aws-mysql-jdbc#327]
Hi,

I plan to use AWS Aurora MySql 8.0 database with the Reactive Relational Database Connectivity (R2DBC) API support. From different articles, MariaDB has the R2DBC connector with MySQL connectivity. Does the AWS community recommend it?

Please let me know if there is any plan to support R2DBC JDBC drivers or any recommendations.

Thanks!

**Comment by karenc-bq** [comment]
Hi @riruvuri, we'll be closing this issue since R2DBC is an alternative to JDBC. If continued discussions around R2DBC are valuable, we can communicate via the discussions tab in the repository. Thanks again for reaching out.

**Comment by pkgonan** [comment]
Is there any support plan for r2dbc? We need failover feature for aurora db(mysql 8.0 compatibility)

**Comment by davecramer** [comment]
You might want to bring this up with the R2DBC folks. It's not currently on our roadmap.
