### ISSUE TITLE
5.6.mysql_aurora.1.22.5 version supported?

### ISSUE THREAD

**Issue by ajsin** [awslabs/aws-mysql-jdbc#328]
Hi.
I'm using 5.6.mysql_aurora1.22.5.

The following error occurs when running the program using the aws-mysql-jdbc driver.
(using openjdk 1.8.0_352)
> Caused by: javax.net.ssl.SSLHandshakeException, The server selected protocol version TLS10 is not accepted by client preferences [TLS12]

The following options were added, but the same error occurred.
`enabledTLSProtocols=TLSv1.2`

Is it because I am using mysql 5.6? Or is there another solution?

Thank you.

**Comment by sergiyvamz** [comment]
Hi @ajsin 

According to RDS documentation, 5.6.mysql_aurora1.22.5 doesn't support TLS1.1 and TLS1.2. https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Security.html

At the same time, AWS JDBC Driver for Mysql is based on Mysql Connector/J 8.0.31 that has deprecated TLS1.0. 
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html#:~:text=For%20Connector/J%208.0.26%20and%20later%3A

I'd also like to pay your attention that parameter `enabledTLSProtocols `has been replaced with `tlsVersions`. Parameter `enabledTLSProtocols `is still available but it's going to be removed soon. Parameter values have changed and allowed values are `TLSv1.2` and` TLSv1.3`.

As a solution for your issue, I can suggest to consider migrating to a later version of Aurora Mysql.

**Comment by ajsin** [comment]
Thanks for your reply.
