### ISSUE TITLE
[QA] what will happen if url path missing aws keyword

### ISSUE THREAD

**Issue by YoungHu** [awslabs/aws-mysql-jdbc#334]
as we known official doc required db url path start with jdbc:mysql:aws://xxxxx, what will happen if db url path start with jdbc:mysql://xxxxx? application can auto switch to new primary write node?

**Comment by davecramer** [comment]
This part you refer to is called the scheme of the URL and it determines which driver is loaded. Unfortunately if you do not have "jdbc:mysql:aws" as the scheme the driver won't even load. So the answer to your question is no it won't switch to the new primary write node

**Comment by YoungHu** [comment]
@davecramer appreciate for your professional reply.
