### ISSUE TITLE
How do I configure jdbc driver(SecretsManagerPlugin) to use UrlConnectionHttpClient instead of org.apache.http.impl.conn.PoolingHttpClientConnectionManager?

### ISSUE THREAD

**Issue by abedali** [awslabs/aws-mysql-jdbc#344]
### Describe the issue

Driver version: 1.1.1

I think JDBC driver internally use 
org.apache.http.impl.conn.PoolingHttpClientConnectionManager
for pulling info from aws infrastructure

We are exploring an option to have driver use  (UrlConnectionHttpClient)
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration-url.html
How do we configure this in the jdbc driver?

### Links

https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration-url.html

**Comment by karenc-bq** [comment]
Hi @abedali, the SecretsManagerPlugin uses the AWS SDK for Secrets Manager which utilizes PoolingHttpClientConnectionManager. The plugin currently does not allow customizing the underlying connection manager in the SDK. 

We have addressed the leaking PoolingHttpClientConnectionManager issue in the driver. Are there other use cases that require such customization?

**Comment by abedali** [comment]
@karenc-bq , we were looking for an alternative approach due to the issue in SecretsManagerPlugin 'leaking PoolingHttpClientConnectionManager'. We shall use an updated driver library once it is available with the fix.

**Comment by karenc-bq** [comment]
We've released a new version of the driver that resolves this issue. Please download the latest 1.1.4 version of the driver. We'll be closing this ticket. Thank you.
