### ISSUE TITLE
IAM connection from example is not working

### ISSUE THREAD

**Issue by goodidea-kp** [awslabs/aws-mysql-jdbc#348]
### Describe the issue

Per my understanding example need to use IamPlugin via *Factory like in case of SecretId `properties.setProperty("connectionPluginFactories", AWSSecretsManagerPluginFactory.class.getName());`

However, the code is not utilizing any plugin, so the connection failed:
`public static void main(String[] args) throws SQLException {
      final Properties properties = new Properties();
      // Enable AWS IAM database authentication
      properties.setProperty("useAwsIam", "true");
      properties.setProperty("user", USER);

      // Try and make a connection
      try (final Connection conn = DriverManager.getConnection(CONNECTION_STRING, properties);
           final Statement statement = conn.createStatement();
           final ResultSet rs = statement.executeQuery("SELECT * FROM employees")) {
         while (rs.next()) {
            System.out.println(rs.getString("first_name"));
         }
      }
   }`

Please provide how to select the proper Factory to utilize NaviteAuthenticationProfider via factory configuration

### Links

https://github.com/awslabs/aws-mysql-jdbc

**Comment by karenc-bq** [comment]
Hi @goodidea-kp, can you please provide the exception stacktrace? The IAM authentication plugin is implemented differently compared to the AWS Secrets Manager plugin and the example shows the correct way to use the plugin.

Can you please verify that
1. IAM database Authentication is enabled for your Aurora MySQL database
2. You are providing the database user as the username instead of the regular master username? 
For example, say I created an IAM database account called `example_user_name` using the command in step 3 of this [documentation](https://github.com/awslabs/aws-mysql-jdbc#setup-for-iam-database-authentication-for-mysql), then my connection properties would be:
```java
      final Properties properties = new Properties();
      // Enable AWS IAM database authentication
      properties.setProperty("useAwsIam", "true");
      properties.setProperty("user", "example_user_name");
```

**Comment by goodidea-kp** [comment]
`

Caused by: java.sql.SQLException: Access denied for user 'userXXX'@'XXXXXX' (using password: YES)
--
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:842) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:462) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:252) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.BasicConnectionProvider.connect(BasicConnectionProvider.java:53) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.DefaultConnectionPlugin.openInitialConnection(DefaultConnectionPlugin.java:104) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.NodeMonitoringConnectionPlugin.openInitialConnection(NodeMonitoringConnectionPlugin.java:268) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.createConnection(FailoverConnectionPlugin.java:1066) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.openInitialConnection(FailoverConnectionPlugin.java:220) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.ConnectionPluginManager.openInitialConnection(ConnectionPluginManager.java:151) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.initPluginManager(ConnectionProxy.java:283) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.<init>(ConnectionProxy.java:104) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.<init>(ConnectionProxy.java:91) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.<init>(ConnectionProxy.java:79) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.autodetectClusterAndCreateProxyInstance(ConnectionProxy.java:126) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:221) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:416) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:128) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:113) ~[aws-mysql-jdbc-1.1.3.jar!/:?]
  | 2023-01-24T10:18:36.340-06:00 | at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159) ~[spring-jdbc-6.0.3.jar!/:6.0.3]
  | 2023-01-24T10:18:36.340-06:00 | at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117) ~[spring-jdbc-6.0.3.jar!/:6.0.3]
  | 2023-01-24T10:18:36.340-06:00 | at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-6.0.3.jar!/:6.0.3]

`

**Comment by karenc-bq** [comment]
Hi @goodidea-kp, the stacktrace suggests it is a permission issue. Could you please verify the following:
1. Are you connecting directly to a specific database? i.e. does your connection string looks like `jdbc:mysql:aws://mysql.cluster-xxx.us-east-2.rds.amazonaws.com/databaseName`. If so can you please verify you have granted the IAM database account permissions via ```GRANT ALL ON `%`.* TO example_user_name@`%`;```? For more information see: https://aws.amazon.com/blogs/database/use-iam-authentication-to-connect-with-sql-workbenchj-to-amazon-aurora-mysql-or-amazon-rds-for-mysql/#:~:text=GRANT%20ALL%20ON%20%60%25%60.*%20TO%20mydbuser%40%60%25%60%3B
2. Could you please clarify what you meant by the aws gen token approach? Did you mean using the AWS CLI to generate the token then connecting via the `mysql` command like the following:
    ```
    TOKEN="$(aws rds generate-db-auth-token --hostname $AURORAEP --port 3306 --username $IAMUSER --region=$REGION)"
    mysql -h ${AURORAEP%%:*} -P 3306  --enable-cleartext-plugin --user=$IAMUSER --password=$TOKEN
    ```

**Comment by goodidea-kp** [comment]
Regarding #2, yes you are correct. I manually generate token and use it as password `aws rds generate-db-auth-token --hostname XXX-hostname --port 3306 --region us-east-1 --username my_user`
for #1, yes user has permissions. If you can tell me what specific I need verify in my `SELECT * FROM mysql.user;` query, I'll do that.

**Comment by karenc-bq** [comment]
Hi @goodidea-kp, here is an simple HikariDataSource example:

```java
  public static void main(String[] args) throws SQLException {
    final HikariConfig config = new HikariConfig();
    config.setJdbcUrl(CONNECTION_URL);
    config.setUsername(USERNAME);
    config.addDataSourceProperty("useAwsIam", "true");

    try (HikariDataSource dataSource = new HikariDataSource(config);
        Connection conn = dataSource.getConnection();
        Statement statement = conn.createStatement();
        ResultSet result = statement.executeQuery("select @@aurora_server_id")) {
      System.out.println(getResult(result));
    }
  }
```

Here is an example configuration for Spring Boot:
```
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql:aws://cluster/db
spring.datasource.username=example_user_name
spring.datasource.hikari.data-source-properties.useAwsIam=true
spring.datasource.driver-class-name=software.aws.rds.jdbc.mysql.Driver
```
