### ISSUE TITLE
Connecting to custom DB cluster results in connection to instance outside the cluster

### ISSUE THREAD

**Issue by krishnasundaresan** [awslabs/aws-mysql-jdbc#362]
### Describe the bug

We have a custom DB cluster that contains a subset of the replicas. However, when this custom DB cluster endpoint is used to make a connection, the connection is made to the writer instance. 

### Expected Behavior

Connection should be made to one of the instances in the custom cluster (as has been called out in the documentation).

### Current Behavior

The connection is established with the writer instance all the time.

### Reproduction Steps

1. Create a custom DB cluster with replicas.
2. Use the endpoint URL to create a connection.
3. Notice the connection has actually been made with the writer instance.

### Possible Solution

This appears to be due to the way the `FailoverConnectionPlugin` handles `setReadOnly` method. In case, the `setReadOnly` method on a connection is called with `false` the current logic identifies the writer node and connects to that.

### Additional Information/Context

Technically this might not even be a bug but a clarification in the docs might suffice? Essentially when using custom DB cluster the connection might be made outside the cluster not only in the case of failover but also to meet `readOnly` semantics,

### The AWS JDBC Driver for MySQL version used

1.1.1

### JDK version used

openjdk 11.0.16 2022-07-19

### Operating System and version

Mac OS Ventura

**Comment by aaronchung-bitquill** [comment]
Hi @krishnasundaresan 
Thanks for reaching out and raising this issue.
We will take a look at this and keep you updated with our investigation. I'll also bring up your concerns with the team. 
In the meantime, could you provide us with some more details as to how you are using the driver? For example:

- How are you connecting to database? (ex. are you using a data frameworks? how are you calling it? )
- Can you show us what configurations you are using? 
- What does the database URL endpoint look like?

Thank you!

**Comment by aaronchung-bitquill** [comment]
@krishnasundaresan Also, are there any logs available that might potentially be signalling failures to connect to reader instances?

**Comment by krishnasundaresan** [comment]
I am connecting to it using plain JDBC. This is the code I was using.
This is a custom endpoint looking like this - `reader.cluster-custom-cayuggg1ecth.<snipped>`

```
public static void main(String[] args) throws SQLException, InterruptedException {
        ExecutorService executorService = Executors.newFixedThreadPool(3);
        System.out.println("Hello world!");

        HikariDataSource replicaDataSource = getDataSource("jdbc:mysql:aws://reader.cluster-custom-cayuggg1ecth.<snipped>");

        for (int j = 0; j < 10; j++) {
            executorService.execute(() -> {
                try (Connection conn = replicaDataSource.getConnection()) {
                    Random random = new Random();
                    for (int i = 0; i < 300; i++) {
                        System.out.println(Thread.currentThread().getName() + " - Iteration " + i);
                        String select_sql = "SELECT sid FROM plugins limit " + random.nextInt(10);
                        try (ResultSet rs = conn.prepareStatement(select_sql).executeQuery()) {
                            while (rs.next()) {
                                System.out.println(rs.getString("sid"));
                            }
                        }
                    }
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            });
        }

        executorService.shutdown();

    }

    private static HikariDataSource getDataSource(String url) {
        final HikariConfig config = new HikariConfig();
        config.setDriverClassName("software.aws.rds.jdbc.mysql.Driver");
        config.setUsername("username");
        config.setJdbcUrl(url);
        config.setPassword("password");
        config.setMaximumPoolSize(10);

        return new HikariDataSource(config);
    }
```

**Comment by krishnasundaresan** [comment]
> @krishnasundaresan Also, are there any logs available that might potentially be signalling failures to connect to reader instances?

I don't have any logs but the monitoring in cloudwatch I could see queries hitting the writer node (which is not part of the custom cluster).

**Comment by aaronchung-bitquill** [comment]
Hi @krishnasundaresan 

Thank you for patience.

The driver does not currently support RDS Custom Clusters. Our documentation does not that make that very clear, so I'd like to apologize if this caused you any inconvenience or frustration. I will be updating the documentation shortly to make sure that this is explicit.

We've created a backlog item for RDS Custom Clusters and will share this feedback with the team.

Please reach out again if you have any other questions or issues. 

Thank you

**Comment by krishnasundaresan** [comment]
> The driver does not currently support RDS Custom Clusters. Our documentation does not that make that very clear, so I'd like to apologize if this caused you any inconvenience or frustration. I will be updating the documentation shortly to make sure that this is explicit.

Documentation actually says the following for custom clusters! So I guess that has to be removed at the least.

![image](https://user-images.githubusercontent.com/109587347/222350342-5dbae6bd-fd35-44e1-aa8b-2c55dba2b869.png)

**Comment by aaronchung-bitquill** [comment]
Thank you for you pointing that out. We'll definitely review that.

**Comment by karenc-bq** [comment]
We have updated the documentation indicating the driver doesn't currently support custom DB Cluster. We will be closing this issue now, thank you for bringing this to our attention.
