### ISSUE TITLE
Redundant "Reset stmt" when setting useServerPrepStmts&cachePrepStmts to true

### ISSUE THREAD

**Issue by sajithkumarkizhakkiniyil** [awslabs/aws-mysql-jdbc#422]
### Describe the bug

This bug also existing in open source version. Please refer to https://bugs.mysql.com/bug.php?id=107107
The is issue get exaggerated in AWS Aurora as the average over the wire latencies are higher
In summary when using Server prepared statements even when you are not switching between long parameters a redundant "Reset stmt" sent over the wire and thus hits with performance issues.

### Expected Behavior

When there is no switching between long parameters we should sent a Reset stmt

### Current Behavior

Currently even when there is no switch it sent a Reset stmt

### Reproduction Steps

Please refer to https://bugs.mysql.com/bug.php?id=107107

### Possible Solution

Set the flag after the after reseting in ServerPreparedQuery.serverResetStatement()
this.queryBindings.setLongParameterSwitchDetected(false) and remove the following code 
this.queryBindings.setLongParameterSwitchDetected(clearServerParameters && hadLongData ? false : true);
from   ServerPreparedQuery.clearParameters

public void serverResetStatement() {
        this.session.checkClosed();
        synchronized (this.session) {
            try {
                System.out.println("serverResetStatement");
                this.session.sendCommand(this.commandBuilder.buildComStmtReset(this.session.getSharedSendPacket(), this.serverStatementId), false, 0);
>>>>>
         if (this.queryBindings != null) {
                 this.queryBindings.setLongParameterSwitchDetected(false);
         }
>>>>
            } finally {
                this.session.clearInputStream();
            }
        }
    }

### The AWS JDBC Driver for MySQL version used

8.0.33

### JDK version used

8

### Operating System and version

any

**Comment by crystall-bitquill** [comment]
Hi @sajithkumarkizhakkiniyil,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by crystall-bitquill** [comment]
Hi @sajithkumarkizhakkiniyil,

We've implemented the fix suggested in the bug report. The fix has been merged and has been included in our latest release, which is version [1.1.9](https://search.maven.org/artifact/software.aws.rds/aws-mysql-jdbc/1.1.9/jar?eh=). We'll be closing this issue now, but if you have any further questions or concerns please feel free to reopen this issue or to create a new one.
