### ISSUE TITLE
Be more verbose about connecting to the read-only endpoint of an aurora RDS instance.

### ISSUE THREAD

**Issue by ls-pieter-vanisacker** [awslabs/aws-mysql-jdbc#456]
### Describe the issue

The doc states that connecting to a RO endpoint can result in connections being created to the RW instance in failover situations.
```
Initial connection: any Aurora Replica
Failover behavior: prioritize connecting to any active Aurora Replica but might connect to the primary DB instance if it provides a faster connection
```

Can you elaborate a bit more on what the logic is? What defines `a faster connection`?

We're currently using this driver and see an occasional connection of our connection pool going to the RW instance although we're using the RO endpoint.
And since our RW instance is heavily loaded some of the queries just time out.

I've been trying to replicate this in an isolated test but haven't been able to do so yet.

### Links

https://github.com/awslabs/aws-mysql-jdbc#connection-url-descriptions

**Comment by crystall-bitquill** [comment]
Hi @ls-pieter-vanisacker, thank you for reaching out.

In the event of a failover, the driver will attempt to connect to other instances in the cluster by iterating through the instances 2 at a time and attempting connections. If one connection succeeds first, the driver will return that connection and stop the other attempt. This instance may be a writer connection. This is what we meant by "a faster connection".

You can set the the `enableFailoverStrictReader` parameter to `true` to prevent connecting to the writer instance during reader failover. Thanks again for raising this, we are adding the missing documentation in PR #457.

**Comment by ls-pieter-vanisacker** [comment]
Perfect, thanks for the quick feedback!
