### ISSUE TITLE
Default clusterId doesn't include user

### ISSUE THREAD

**Issue by b1tninja** [awslabs/aws-mysql-jdbc#460]
We have a rds cluster that we access with multiple users, and when there is a conneciton failover the connection pool would sometimes reconnect with the wrong credentials. We noticed becuase the users don't have access to the same tables, so we would see `SELECT command denied to user` .

After looking through the FailoverConnectionPlugin code I noticed that the clusterId defaults to the RDS cluster host:port, which would be the same regardless of user. I suspect that the connection manager is getting a cached topology with a HostInfo for the "other" user.

Would it be safer to include the username in the default clusterId?
https://github.com/awslabs/aws-mysql-jdbc/blob/2a87614e3359e255fbf3553e860dd018ace68557/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L1229

**Comment by crystall-bitquill** [comment]
Hi @b1tninja,

Thanks for reaching out and raising this issue.

We'll keep you updated as we investigate.

In the meantime, I have a few questions:
- What version of the driver are you using? In the latest version of the driver, the topology cache keeps the host, port, and other properties that come from the topology query. Any connection-specific properties (including the username, password, etc.) should not be in the topology cache. The connection specific properties used to be stored in the topology cache, but this was changed in version 1.1.8. 
- How is your connection pool configured and what properties are being used? Are you using multiple connection pools?

Thank you!

**Comment by b1tninja** [comment]
Ah ok, dang I thought I was on to something since I saw HostInfo has user and password variables.

We are using aws-java-sdk-rds-1.11.943.jar and notice the issue when a connection drops and reconnects, we can trigger it by failing over the db.

We've got an support case open about it, I'll close this issue since the user/pass aren't used.

Thanks!
