### ISSUE TITLE
Relax overly-strict query type checking of "Results Producing" QueryReturnType, or provide override flag for batchUpdate()

### ISSUE THREAD

**Issue by benkanlu** [awslabs/aws-mysql-jdbc#465]
### Describe the feature

Currently the QueryInfo.getQueryReturnType checks to see if the SQL may return any results. If it does and the underlying method called (specifically jdbcTemplate.batchUpdate(sql)) is called, it throws an error saying it is not allowed. 

"Caused by: org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [
-- ]; Statement.executeUpdate() or Statement.executeLargeUpdate() cannot issue statements that produce result sets."

### Use Case

There are many use cases to use 'CALL/EXECUTE' or even other things like 'OPTIMIZE' or 'REPAIR' in an automated way by sending multiple statements through batchUpdate(), which reduces communication overhead. If it does return anything (like in an OPTIMIZE table for example), the results can just be ignored or discarded.

Previously, MySQL/MariaDB native drivers allowed this type of 'ignoring' results sets if a non-DML statement (i.e. DDL/DCL) was sent. 

### Proposed Solution

While tightening down the types of statements allowed in a batchUpdate() may work in many cases, an option/flag to override this functionality would help immensely with current code bases expecting such functionality. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS JDBC Driver for MySQL version used

Any version greater than 0.4.0 causes this issue.

### JDK version used

OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS)

### Operating System and version

Windows 10 / Ubunutu 18.04

**Comment by crystall-bitquill** [comment]
Hi @benkanlu,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by crystall-bitquill** [comment]
Hi @benkanlu,

After some consideration, we have decided that we will not be implementing this feature.

This is for two reasons:
1. The AWS JDBC Driver for MySQL is based on the [MySQL Connector/J driver](https://github.com/mysql/mysql-connector-j), and we would like to remain as consistent with it as possible. As this would be altering/adding to the existing functionality, we are a bit hesitant to make changes of this magnitude. Have you considered making this suggestion for the MySQL Connector/J driver?
2. As noted in our [maintenance policy](https://github.com/awslabs/aws-mysql-jdbc/blob/main/RELEASE_POLICY.md), new features will not be added to the AWS JDBC Driver for MySQL going forward.

Thank you for raising this issue. This ticket will be closed, but please feel free to reach out again if you have other questions.

**Comment by benkanlu** [comment]
Thanks you... I have moved on to using the AWS Advanced Wrapper driver that is (for now) the recommended method.  [AWS Advanced JDBC Wrapper](https://github.com/awslabs/aws-advanced-jdbc-wrapper). I have it all working fine there now with Aurora Mysql/Mariadb and Aurora Postgres. Not painless, but at least it allows us to use MariaDB still which does not have this issue noted above. Thanks, again!

**Comment by hsuamz** [comment]
> Thank you... I have moved on to using the AWS Advanced Wrapper driver that is (for now) the recommended method. [AWS Advanced JDBC Wrapper](https://github.com/awslabs/aws-advanced-jdbc-wrapper). I have it all working fine there now with Aurora Mysql/Mariadb and Aurora Postgres. Not painless, but at least it allows us to use MariaDB still which does not have this issue noted above. Thanks, again!

Thanks for sharing your experience @benkanlu. If I could ask, you mentioned that moving to the Wrapper was "not painless". Would you be able to share some feedback around this? We would definitely be interested in hearing more as we want to continuously improve the experience with using the Wrapper. Thank you again!

**Comment by benkanlu** [comment]
The biggest pain-point is around if you are using Hikari for your connection pooling (most people are in this scenario, I believe). "When using the AwsWrapperDataSource you must specify the dataSourceClassName, therefore HikariDataSource.setJdbcUrl is not supported.". See bottom of this page for reference [HikariCP with Advanced Wrapper driver](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/DataSource.mdl).

Because you can no longer use HikariCP's 'setJDBC' method, it means you have to basically write your own JDBC URL Parser to correctly set all of the required elements include Platform, Server, Port, Database name, and also all of the JDBC Properties. Handling all of the platform flavors of JDBC URLs (MySQL, MariaDB, Postgres, Aurora vs non-Aurora) and error handling for malformed URLs is doable, but tedious. 

Ideally, AWS should provide some built-in JDBC URL Parser libraries now that their Wrapper driver no longer works the same with Hikari. I could be wrong, but I think many people using HikariCP will avoid using the Wrapper driver until this is available.  There just aren't a lot of great open source JDBC URL parsers out there right now (that I could find at least).

As a side note to bring this back to the original Issue I raised here around the batchUpdate(), I am now able to continue to use MariaDB drivers with the Advanced JDBC Wrapper driver (using our own custom JDBC URL parser).

**Comment by crystall-bitquill** [comment]
Hi @benkanlu,

Thank you for your feedback!

To clarify, it is possible use a JDBC URL with HikariCP and the Wrapper Driver. Instead of configuring the URL through the HikariCP `setJdbcUrl` method, however, it would have to be configured through the `AwsWrapperDataSource`. The [`AwsWrapperDataSource`](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/DataSource.md) allows users to set individual JDBC properties or to set the JDBC URL.

With HikariCP, it would look like this:
```java
HikariDataSource ds = new HikariDataSource()

// Configure the connection pool:
ds.setUsername(USER);
ds.setPassword(PASSWORD);

// Specify the underlying datasource for HikariCP:
ds.setDataSourceClassName(AwsWrapperDataSource.class.getName());

// Configure AwsWrapperDataSource:
ds.addDataSourceProperty(
    "jdbcUrl",
    "jdbc:aws-wrapper:mysql://db-identifier.cluster-XYZ.us-east-2.rds.amazonaws.com:3306/test");

// Specify the driver-specific data source for AwsWrapperDataSource:
ds.addDataSourceProperty("targetDataSourceClassName", "com.mysql.cj.jdbc.MysqlDataSource");
```

Apologies for the confusion, I've opened a [PR](https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/749) for the AWS JDBC Driver to make the documentation clearer.

**Comment by benkanlu** [comment]
Yes, the parsing seems to work fine as long as you stay with 'jdbc:aws-wrapper:mysql'. Do you have an example of how to get it to work with Mariadb? It does not seem to work with Mariadb, yet. I've tried 'jdbc:aws-wrapper:mariadb:', but get a "ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization. 
java.lang.UnsupportedOperationException: ConnectionStringHostListProvider does not support getHostRole". 

I have tried setting it with "addDataSourceProperty("targetDataSourceClassName", "org.mariadb.jdbc.MariaDbDataSource");", but that just results in another URL error "ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization. 
java.sql.SQLException: Wrong mariaDB url"

We really need Mariadb support for the original request in this Feature request (MySQL isn't play nice with batchUpdate(). I'd love to use the built-in aws-wrapper JDBC URL parser if it actually works with Mariadb.

Thanks for your help!

**Comment by karenc-bq** [comment]
HI @benkanlu, could you please try appending `?permitMysqlScheme` to your JDBC url?
As an example:
```java
ds.addDataSourceProperty(
    "jdbcUrl",
    "jdbc:aws-wrapper:mysql://db-identifier.cluster-XYZ.us-east-2.rds.amazonaws.com:3306/test?permitMysqlScheme");
ds.addDataSourceProperty("targetDataSourceClassName", "org.mariadb.jdbc.MariaDbDataSource");
```

**Comment by karenc-bq** [comment]
Hi @benkanlu, which version of the wrapper are you using? We recently released [version 2.3.1](https://github.com/awslabs/aws-advanced-jdbc-wrapper/releases/tag/2.3.1) of the wrapper that [addresses](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/aa5ae6168c738d7870d7cb05f431f697a7c85b21/wrapper/src/main/java/software/amazon/jdbc/ds/AwsWrapperDataSource.java#L132) the issue you mentioned. Could you please let me know if the issue persists with v2.3.1? Thank you!

**Comment by benkanlu** [comment]
Ah, I had updated to 2.3.0 just the day before you released 2.31! :)  (Maybe this whole conversation should be moved over to the Advanced Wrapper github repo so that others can see it? Thoughts?)

Ok, I was able to get it to work with your example against a Aurora cluster. 

In my testing, I did notice that the same format did not work against a localhost connection (running mariadb on my workstation). See example in below. Also, ideally it would be nice to have the wrapper detect on the prefix 'jdbc:aws-wrapper:mariadb:' if you are connecting to an aurora cluster. It seems to only work for localhost.

So, I think we are close to achieving the goal of "Use MariaDB driver, but also use the aurora-mysql dialect when connected to an Aurora cluster."  I just think it would be way more intuitive to others to not have to use the 'jdbc:aws-wrapper:mysql ... ?permitMysqlScheme' in order for to translate to MariaDB under the covers for you. 

Here are the combinations that seem to have worked and not worked so far:




<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


JDBC   URL | Acutal Driver Used | Actual Dialect Used | Succes or Error?
-- | -- | -- | --
jdbc:aws-wrapper:mariadb://localhost:3306/yourdatabase | mariadb | mariadb | Success
jdbc:aws-wrapper:mariadb://localhost:3306/yourdatabase?permitMysqlScheme | mariadb | mariadb | Success
  |   |   |  
jdbc:aws-wrapper:mysql://localhost:3306/yourdatabase | mysql | mysql | Success (issues still with batchUpdate(), due to mysql driver)
jdbc:aws-wrapper:mysql://localhost:3306/yourdatabase?permitMysqlScheme |   |   | Error:   "software.amazon.jdbc.exceptions.SQLLoginException: The target driver   did not return a connection.")
  |   |   |  
jdbc:aws-wrapper:mysql://somecluster.us-east-1.rds.amazonaws.com:3306/yourdatabase?permitMysqlScheme | mariadb | aurora-mysql | Success
jdbc:aws-wrapper:mysql://somecluster.us-east-1.rds.amazonaws.com:3306/yourdatabase | mysql | aurora-mysql | Success (issues still with batchUpdate(), due to mysql driver)
  |   |   |  
jdbc:aws-wrapper:mariadb:/somecluster.us-east-1.rds.amazonaws.com:3306/yourdatabase |   |   | ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 -   Exception during pool initialization.
  |   |   | java.lang.UnsupportedOperationException:   ConnectionStringHostListProvider does not support getHostRole
  |   |   |  
jdbc:aws-wrapper:postgresql://localhost:5432/yourdatabase?currentSchema=yourschema | postgresql | pg | Success
jdbc:aws-wrapper:postgresql://somecluster.us-east-1.rds.amazonaws.com:5432/yourdatabase?currentSchema=yourschema | postgresql | aurora-pg | Success



</body>

</html>

**Comment by crystall-bitquill** [comment]
Hi @benkanlu,

Good idea, we can move this discussion over to the wrapper repo. Would you like to crete a new issue there, or should we create it?

To give some context, the wrapper is meant to be functional with different databases, making it necessary for it to be able to identify which database is being connected to in order to perform database-specific operations. The database-specific operations are contained in [database dialects](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/DatabaseDialects.md). The wrapper uses the protocol to identify which database dialect to use and the wrapper does not depend on the underlying driver to make that decision. For example, if connecting to a MariaDB database, the dialect should be `mariadb`. When connecting to an Aurora MySQL database, the dialect should be `aurora-mysql`.

For the protocol, the wrapper delegates calls to a target driver that can accept the given protocol. The MariaDB protocol (`jdbc:aws-wrapper:mariadb:`) is accepted by the MariaDB driver, but the MySQL protocol (`jdbc:aws-wrapper:mysql`) is accepted by multiple drivers, including the MariaDB driver. However, when using the MySQL protocol with the MariaDB driver, the permitMysqlScheme parameter is also required. 

For the SQLLoginException, which driver and dialect were used for this case? It seems the target driver didn't return a connection, but we would need a full stack trace to investigate this further.

**Comment by benkanlu** [comment]
If you can create a new issue and move this over to the aws-wrapper repository, that would be great. Not sure what the process is to keep our previous dialogue (if necessary).

So, the spreadsheet above with the columns **'Actual Driver Used** / **Actual Dialect Used**', is not me explicitly setting those dialects (like I did in my Custom JDBC URL parser scenario), but letting your aws-wrapper driver do it's magic and figure out the correct driver. I just put those columns in there to track what was actually used (by looking at the value in Debug mode at Springs **JdbcTemplate.java** under the _con->delegate->hostListProviderService->dialectProvider->dialectCode_ variable that gets set. I am able to see what you guys are setting without assuming the dialect is correct. The places I kept blank in those columns is where there was an error ( like the SQLLoginException error) and never made it far enough to establish a connection.

Because my application connects to multiple platform types (Aurora Mysql, Mariadb, and Postgresql, Aurora Postrgresql), I actually do not want to have to set the wrapperDialect at all, but just rely on your aws-wrapper driver to do that. Otherwise, I'm back to having to parse at least part of the jdbc url to determine which wrapperDialect to set it to.

As long as you use the "jdbc:aws-wrapper:**mysql**://somecluster.us-east-1.rds.amazonaws.com:3306/yourdatabase**?permitMysqlScheme**", it uses the mariadb/aurora-mysql combination just fine. I'm just suggesting your wrapper detects "jdbc:aws-wrapper:**mariadb**:/somecluster.us-east-1.rds.amazonaws.com:3306/yourdatabase" the same way. 

The only code I need to get this all to work is basically (which works great!):
               
**setDataSourceClassName(AwsWrapperDataSource.class.getName());
addDataSourceProperty("jdbcUrl", url);**
