### ISSUE TITLE
getHoldability() and getResultSetHoldability() return different results

### ISSUE THREAD

**Issue by dwenking** [awslabs/aws-mysql-jdbc#483]
### Describe the bug

I find that when I obtain a new Statement object, the ResultSetHoldability it retrieves is 1.  However, when I create a ResultSet using this Statement and try to get its Holdability value, it throws an error. 

### Expected Behavior

I find this confusing because I expect these two methods to behave consistently.

### Current Behavior

See bug description.

### Reproduction Steps

```java
@Test
public void test() throws SQLException {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?user=user&password=password");
    Statement stmt = con.createStatement(1003, 1008, 1);
    System.out.println(stmt.getResultSetHoldability());
    ResultSet rs = stmt.executeQuery("SELECT 1;");
    System.out.println(rs.getHoldability()); // expect return the same results as stmt.getResultSetHoldability() 
}
```

### The AWS JDBC Driver for MySQL version used

1.1.10

### JDK version used

20

### Operating System and version

Windows

**Comment by brunos-bq** [comment]
Hi @dwenking,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by crystall-bitquill** [comment]
Hi @dwenking,

After some consideration, we've decided we will not be implementing a fix for this issue. 

Looking at the code, the default holdability value is `HOLD_CURSORS_OVER_COMMIT` and `CLOSE_CURSORS_AT_COMMIT` does not seem to be supported. Some getHoldability or getResultSetHoldability methods return constant values, and others throw an exception. To make these methods consistent, the potential solutions would be:
1. to have all get holdability methods return `HOLD_CURSORS_OVER_COMMIT`, as that is the default value.
2. to have all get holdability methods throw an exception, as is done in the `ResultSetImpl` and `UpdatableResultSet` classes.

The AWS JDBC Driver for MySQL is based on the [MySQL Connector/J driver](https://github.com/mysql/mysql-connector-j) and we would like to remain as consistent with it as possible. Therefore, it is difficult for us to determine which approach to take as we would be changing which methods automatically throw exceptions. In this case, we will defer to the existing code and leave it as-is.

This issue will be closed, but please feel free to reach out again if you have other questions. Thank you!
