### ISSUE TITLE
Error Initializing DB Connection to Aurora DB in `AWS-CN` without `enableClusterAwareFailover=false`

### ISSUE THREAD

**Issue by hippozhengsc** [awslabs/aws-mysql-jdbc#503]
### Describe the bug

Create an Aurora DB in AWS-CN Region like cn-north-1. and notice the url of the DB Cluster endpoint is something like the following: `db-identifier.cluster-XYZ.cn-north-1.rds.amazonaws.com.cn:3306`

And this URL should be regarded as an acceptable AWS RDS cluster URL and the failover should be enabled by default.

### Expected Behavior

enableClusterAwareFailover=false is not required for aurora DB created in `aws-cn`

### Current Behavior

The following error is thrown out without the parameter:

Caused by: java.sql.SQLException: The clusterInstanceHostPattern configuration property is required when an IP address or custom domain is used to connect to a cluster that provides topology information. If you would instead like to connect without failover functionality, set the enableClusterAwareFailover configuration property to false.
12:16:01    [sshexec] 	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.initExpectingNoTopology(FailoverConnectionPlugin.java:972)
12:16:01    [sshexec] 	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.initProxy(FailoverConnectionPlugin.java:1019)
12:16:01    [sshexec] 	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.openInitialConnection(FailoverConnectionPlugin.java:248)
12:16:01    [sshexec] 	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.ConnectionPluginManager.openInitialConnection(ConnectionPluginManager.java:151)
12:16:01    [sshexec] 	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.initPluginManager(ConnectionProxy.java:293)
12:16:01    [sshexec] 	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.<init>(ConnectionProxy.java:107)
12:16:01    [sshexec] 	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.<init>(ConnectionProxy.java:93)
12:16:01    [sshexec] 	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.<init>(ConnectionProxy.java:81)
12:16:01    [sshexec] 	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.autodetectClusterAndCreateProxyInstance(ConnectionProxy.java:129)
12:16:01    [sshexec] 	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:221)
12:16:01    [sshexec] 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
12:16:01    [sshexec] 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)

### Reproduction Steps

- Create an Aurora DB in AWS-CN Region like cn-north-1. and notice the url of the DB Cluster endpoint is something like the -following: `db-identifier.cluster-XYZ.cn-north-1.rds.amazonaws.com.cn:3306`
- use the following jdbc url to establish a connection

jdbc:mysql:aws://db-identifier.cluster-XYZ.cn-north-1.rds.amazonaws.com.cn:3306

### Additional Information/Context

N/A

### The AWS JDBC Driver for MySQL version used

com.amazonaws:aws-java-sdk-secretsmanager:1.11.681

### JDK version used

openjdk version "11.0.19" 2023-04-18 OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7) OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (build 11.0.19+7, mixed mode)

### Operating System and version

MacOS, Linux

**Comment by crystall-bitquill** [comment]
Hi @hippozhengsc,

Thanks for reaching out and raising this issue. We've recently merged in a PR (#543) to address this. Could you kindly check out our latest [snapshot build](https://github.com/awslabs/aws-mysql-jdbc?tab=readme-ov-file#using-a-snapshot-of-the-driver) and let us know if the issue persists?

And to let you know, while the AWS JDBC Driver for MySQL is still being maintained at the moment, new features will no longer be added to the driver and all future developments will take place in the [AWS JDBC Driver](https://github.com/awslabs/aws-advanced-jdbc-wrapper) project. More details can be found on the [maintenance policy](https://github.com/awslabs/aws-mysql-jdbc/blob/main/RELEASE_POLICY.md#maintenance-policy). We encourage users of the AWS JDBC Driver for MySQL to try out the AWS JDBC Driver, as it provides similar and additional features. There is a migration guide available [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#aws-jdbc-driver-for-mysql-migration-guide).

Thank you!

**Comment by philipogormanjca** [comment]
I got this error connecting using JetBrains datagrip, i switched the driver to "MariaDB driver for Auorora MySQL" and the error went away

**Comment by philipogormanjca** [comment]
I tried 1.1.9 and i got the errror

**Comment by crystall-bitquill** [comment]
Hi @philipogormanjca,

It looks like JetBrains DataGrip does not have the latest version of the driver. Are you able to download the driver JAR from our latest release and use it in DataGrip? The `aws-mysql-jdbc-1.1.14.jar` file is available [here](https://github.com/awslabs/aws-mysql-jdbc/releases/tag/1.1.14) and it looks like users should be able to specify custom JAR files in DataGrip, as seen [here](https://www.jetbrains.com/help/datagrip/other-databases.html#using-user-driver-files).

**Comment by marcosfreitas** [comment]
In this version 1.1.14 I got this error:

![image](https://github.com/awslabs/aws-mysql-jdbc/assets/1065688/cc533991-d925-48ae-9b6c-898bbd27a2af)

![image](https://github.com/awslabs/aws-mysql-jdbc/assets/1065688/e6e8adcd-340c-4bb5-b016-32dfb7ca8123)

**Comment by aaronchung-bitquill** [comment]
Hi @marcosfreitas 

Just to double check, are you also connecting to an Aurora DB cluster in AWS-CN? 

Additionally, are there any other settings/properties that you may be using that you are able to share? 

Thank you!

**Comment by marcosfreitas** [comment]
Hi @aaronchung-bitquill , no additional settings. It was a fresh installed Data Grip. I also tried to connect using the cluster address.

**Comment by aaronchung-bitquill** [comment]
@marcosfreitas can you share what your the endpoints you are using look like, and with the secret information redacted?

**Comment by davecramer** [comment]
Support for this driver will be ending July 25/2024 as per the https://github.com/awslabs/aws-mysql-jdbc/blob/main/CONTRIBUTING.md document. Any new features will be implemented in https://github.com/aws/aws-advanced-jdbc-wrapper
