### ISSUE TITLE
Statement.cancel() does not work

### ISSUE THREAD

**Issue by kassak** [awslabs/aws-mysql-jdbc#527]
### Describe the bug

Statement.cancel() does not work as it is invoked through `software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy.JdbcInterfaceProxy#invoke` which synchronises on statement instance.
As the result if I have the long running `execute()` (eg `select sleep(314159265)`) and trying to cancel it from another thread, cancel operation would wait until execute completes. That is definitely not the way cancel should work :)

### Expected Behavior

Statement immediately canceled in the database, execute is immediately aborted with exception.

### Current Behavior

Cancel is hung until execute completes

### Reproduction Steps

execute `select sleep(314159265)` on one thread and try to cancel statement from another thread

### The AWS JDBC Driver for MySQL version used

1.1.9

### JDK version used

21

### Operating System and version

Linux 6.6.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 02 Jan 2024 02:28:28 +0000 x86_64 GNU/Linux

**Comment by crystall-bitquill** [comment]
Hi @kassak,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

And to let you know, while the AWS JDBC Driver for MySQL is still being maintained at the moment, new features will no longer be added to the driver and all future developments will take place in the [AWS JDBC Driver](https://github.com/awslabs/aws-advanced-jdbc-wrapper) project. More details can be found on the [maintenance policy](https://github.com/awslabs/aws-mysql-jdbc/blob/main/RELEASE_POLICY.md#maintenance-policy). We encourage users of the AWS JDBC Driver for MySQL to try out the AWS JDBC Driver, as it provides similar and additional features. There is a migration guide available [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#aws-jdbc-driver-for-mysql-migration-guide).

Thank you for you patience!

**Comment by crystall-bitquill** [comment]
Hi @kassak,

We've recently merged in a fix (#531). Could you kindly check out our latest [snapshot](https://github.com/awslabs/aws-mysql-jdbc?tab=readme-ov-file#using-a-snapshot-of-the-driver) build and let us know if the issue persists?

Thank you!

**Comment by crystall-bitquill** [comment]
Hi @kassak,

The fix for this issue is now available on the [latest version](https://search.maven.org/artifact/software.aws.rds/aws-mysql-jdbc/1.1.14/jar?eh=) of the AWS JDBC Driver for MySQL. If there are no further updates on this ticket in the next few days, it will be closed. Please feel free to reopen this issue or to create a new one if the issue persists or if you have additional questions or concerns.

Thank you!
