### ISSUE TITLE
what is the different between aws-mysql-jdbc and aws-advanced-jdbc-wrapper

### ISSUE THREAD

**Issue by yhjhoo** [awslabs/aws-mysql-jdbc#549]
### Describe the issue

seems both driver provide the similar function, why two in the same awslabs?

### Links

document link here

https://github.com/awslabs/aws-advanced-jdbc-wrapper

https://github.com/awslabs/aws-mysql-jdbc

**Comment by brunos-bq** [comment]
Hello @yhjhoo,

That is an excellent question.

The AWS MySQL JDBC driver, as it name explicitely says, is a MySQL JDBC driver built on top of the [MySQL-Connector-J JDBC](https://github.com/mysql/mysql-connector-j) driver to provide features and enhancements of Amazon Aurora databases to that driver. That means that that an user can only use the AWS MySQL JDBC driver with MySQL databases and/or MySQL compatible Amazon RDS and Amazon Aurora clusters.

The AWS JDBC Driver, as you mentioned in the issue, provides similar functionalities. However, it is not specific to a certain vendor database. The idea of this driver is to build a feature/functionality layer for JDBC on top of an existing database driver. It currently supports not only MySQL, but also PostgreSQL and MariaDB.

In that sense, one could see the functionalities in AWS MySQL driver as a small subset of the functionalities of the AWS JDBC Driver.

Once the AWS JDBC Driver was released, it was decided to not proceed with any new functionalities work in the AWS MySQL JDBC Driver. In that sense, the AWS MySQL JDBC Driver is now behind in terms of functionalities, only receiving security and critical fixes.

It is mentioned in the AWS MySQL Driver [documentation](https://github.com/awslabs/aws-mysql-jdbc/blob/main/README.md#known-limitations) that all new feature work would be only available in the AWS JDBC Driver, and that all users should consider migrating to the AWS JDBC Driver sooner than later. One will also find in the [Maintenance Policy](https://github.com/awslabs/aws-mysql-jdbc/blob/main/RELEASE_POLICY.md#maintenance-policy) section of the documentation that the driver will be discontinued soon in July 2024.

In the documentation of the AWS JDBC Driver, there is a [section to guide users](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#aws-jdbc-driver-for-mysql-migration-guide) in the process of migrating from the AWS MySQL JDBC Driver to the AWS JDBC Driver.

If you are new to the projects and are wondering which one to use, you should definitely use the [AWS JDBC Driver](https://github.com/awslabs/aws-advanced-jdbc-wrapper).

I hope this answers your question and/or clarifies any doubts you might have.

Feel free to comment on whether this was helpful or whether the documentation was a bit unclear about it.

If we don't hear from you within the next week, we will close this ticket and consider it resolved.

Thanks!

**Comment by myoffe** [comment]
May I suggest that this information be added somewhere prominent in the README of this project?
It took me a bit of digging to understand the differences and state of both projects, until I found this discussion page.
🙏
