### ISSUE TITLE
Is it possible to exclude Readers with different instance types if they are included?

### ISSUE THREAD

**Issue by dekachiri** [awslabs/aws-mysql-jdbc#567]
### Describe the issue

The documentation states that custom endpoints are not supported.

Is it possible to exclude only `db-instance-4` when connecting to Reader with the following cluster?

```
db-instance-1: 4xlarge, writer
db-instance-2: 4xlarge, reader
db-instance-3: 4xlarge, reader
db-instance-4: large, reader
```

### Links

https://github.com/awslabs/aws-mysql-jdbc#connection-url-descriptions

**Comment by davecramer** [comment]
Strongly recommend you move to the https://github.com/awslabs/aws-advanced-jdbc-wrapper we won't be adding any new features to this driver

**Comment by dekachiri** [comment]
Thanks for the answer.
I will check this out.
