### ISSUE TITLE
MonitorConnectionContext queue cause memory leak

### ISSUE THREAD

**Issue by ftasso** [awslabs/aws-mysql-jdbc#585]
### Describe the bug

Hello,
using the driver v1.1.15 version, in Monitor class, Queue<MonitorConnectionContext> just have add in startMonitoring and run method, no remove in stopMonitoring method, this will cause memory leak.

### Expected Behavior

remove unused MonitorConnectionContext in queue.

### Current Behavior

![AWS-Jdbc_memory_leak](https://github.com/awslabs/aws-mysql-jdbc/assets/63312108/ea9aea93-84d3-4f14-8751-448b62cbd348)

### Reproduction Steps

integrate aws driver and run application monitor the class instance

### The AWS JDBC Driver for MySQL version used

v1.1.15

### JDK version used

openjdk version "1.8.0_382"

### Operating System and version

NAME="Amazon Linux" VERSION="2" ID="amzn" ID_LIKE="centos rhel fedora" VERSION_ID="2" PRETTY_NAME="Amazon Linux 2" ANSI_COLOR="0;33" CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2" HOME_URL="https://amazonlinux.com/"

**Comment by aaronchung-bitquill** [comment]
Hi @ftasso 

Thanks for reaching out and raising this issue. This is currently a known issue. For a workaround, can you try the experimental [Host Monitoring Plugin v2](https://github.com/awslabs/aws-mysql-jdbc/blob/main/README.md#experimental-enhanced-failure-monitoring-plugin-v2)? The Host Monitoring Plugin v2 is functionally equivalent to the Host Monitoring Plugin and they are configured using the same parameters. The Host Monitoring Plugin v2 was created to address the issues that you have been experiencing, and it is meant to be a more stable version of the Host Monitoring Plugin. As it is currently an experimental plugin, please note that it should be tested before being used in a production environment.

However, I highly recommend migrating from the AWS MySQL JDBC driver to the [AWS Advanced JDBC Wrapper Driver](https://github.com/aws/aws-advanced-jdbc-wrapper). As per the maintenance policy ([linked here](https://github.com/awslabs/aws-mysql-jdbc/blob/main/RELEASE_POLICY.md#maintenance-policy)), the AWS MySQL JDBC Driver maintenance windows ends very soon on July 25, 2024. The AWS Advanced JDBC Wrapper Driver has all of the same features and more, and is actively being supported and developed. 

Thank you!

**Comment by ftasso** [comment]
Hello,
many thanks for your reply.
Ok I got it, I will start che evaluation of the Plugin V2 asap and I will schedule the migration to the advanced JDBC Wrapper Driver.

Bye!
Fabrizio

**Comment by aaronchung-bitquill** [comment]
Hi @ftasso 

Wanted make sure you are aware that we have a bug with the Host Monitoring Plugin V2 that may result in `java.util.ConcurrentModificationException`. 

However, the fix has recently been merged in and available on the latest snapshot build. If you don't mind trying out a snapshot version, could you kindly checkout our [snapshot](https://github.com/awslabs/aws-mysql-jdbc#using-a-snapshot-of-the-driver) build and let us know if the issue still persists?

Thank you!

**Comment by davecramer** [comment]
Closing due to lack of response

**Comment by ftasso** [comment]
Hello,
sorry for my late reply.
I made a new build of my app using the jar file aws-mysql-jdbc-1.1.16-20240624.122534-5.jar with HostMonitoringPluginV2 and I finally forgot the memory leaks.

Thank you,
Fabrizio

**Comment by davecramer** [comment]
@ftasso has this been resolved then ?
