### ISSUE TITLE
Hikaricp connection aliver check blocked five minutes while rds master failover 

### ISSUE THREAD

**Issue by gavenpeng** [awslabs/aws-mysql-jdbc#612]
### Describe the bug

In one of our business applications, we are using HikariCP with the AWS MySQL JDBC driver. After an AWS RDS primary-secondary failover, HikariCP performs a connection validation check when attempting to acquire a connection. According to our logs, after the RDS failover (which occurred around 9:00 AM on August 18th due to an issue with the AWS EBS volumes, with the previous primary taking approximately 5 minutes to recover), HikariCP's connection validation checks were taking an unexpectedly long time—about 5 to 6 minutes. Eventually, an exception was thrown: "The active SQL connection has changed due to a connection failure. Please re-configure session state if required." This entire process, from the start of the validation check to the exception being thrown, took 5 to 6 minutes, until the previous master fully recovered，leading to significant thread exhaustion and blocking，

### Expected Behavior

fast failed

### Current Behavior

blocked 

### Reproduction Steps

master failover but origin master is not recovery normal, until the previous master fully recovered

### The AWS JDBC Driver for MySQL version used

1.1.7.2

### JDK version used

1.8.0

### Operating System and version

ec2 host

**Comment by gavenpeng** [comment]
![jdbc-cost](https://github.com/user-attachments/assets/7a174430-70df-4157-956a-b4c25125a4e4)

**Comment by gavenpeng** [comment]
looked jdbc code, found do failover whiel exec sql failed ,the failover blocked max time five minutes, until the reconnect master success.

**Comment by karenc-bq** [comment]
Hi @gavenpeng, this is expected behaviour.

The message:
```
The active SQL connection has changed due to a connection failure. Please re-configure session state if required.
```
is thrown when the AWS MySQL JDBC Driver has completed a successful driver-sided failover. When the RDS failover happened on the server side and instances became unavailable, the failed connections triggered the driver's failover feature. 

You can disable driver sided failover by setting the connection property `enableClusterAwareFailover` to `false` if you'd like a fast fail behaviour.

Please note that support for this driver has ended as of July 25/2024. We recommend that you migrate to the new [AWS Advanced Wrapper Driver](https://github.com/aws/aws-advanced-jdbc-wrapper), as all new features will be implemented there.

**Comment by gavenpeng** [comment]
> Hi @gavenpeng, this is expected behaviour.
> 
> The message:
> 
> ```
> The active SQL connection has changed due to a connection failure. Please re-configure session state if required.
> ```
> 
> is thrown when the AWS MySQL JDBC Driver has completed a successful driver-sided failover. When the RDS failover happened on the server side and instances became unavailable, the failed connections triggered the driver's failover feature.
> 
> You can disable driver sided failover by setting the connection property `enableClusterAwareFailover` to `false` if you'd like a fast fail behaviour.
> 
> Please note that support for this driver has ended as of July 25/2024. We recommend that you migrate to the new [AWS Advanced Wrapper Driver](https://github.com/aws/aws-advanced-jdbc-wrapper), as all new features will be implemented there.

thanks reply, the error message 

`The active SQL connection has changed due to a connection failure. Please re-configure session state if required.`
is ok, is thrown while failover successful, the main problem is blocked application thread five minutes while failover can't complete until five minute timeout, the timeout is config by set params failoverTimeoutMs, we config 30 seconds

i will migrate to new aws advanced wrapper driver.

**Comment by gavenpeng** [comment]
@karenc-bq the params of failoverTimeoutMs default is five minute, is too big,  Will it be optimized in aws advanced wrapper driver，thanks
