### ISSUE TITLE
How do I configure logging levels?

### ISSUE THREAD

**Issue by jaakko-solita** [awslabs/aws-mysql-jdbc#63]
- [   ] bug report
- [ x ] feature request
    
**Describe the issue**
This library is logging quite a lot. I see log lines with level TRACE. I would like to see only INFO level log lines and up

I'm using Spring Boot and Hikari. The driver seems to do custom logging outside the usual logging framework? How do I configure the log levels?

**Driver Version?** 
0.1.0

**Comment by hsuamz** [comment]
Closing this issue as this is an enhancement. The request is captured here for reference and consideration for the future: https://github.com/awslabs/aws-mysql-jdbc/discussions/241.
