### ISSUE TITLE
is it recommended to use for production?

### ISSUE THREAD

**Issue by mealbarracin10** [awslabs/aws-mysql-jdbc#95]
**Describe the issue**
I'm evaluating this driver to use on my application, but on the readme file I can see that say _We encourage you to experiment with MySQL driver but DO NOT adopt it for production use_ So My question is I can see the 0.1.0 and 0.2.0 versions is it recommended to use any version on production

**Driver Version?** 
0.1.0
0.2.0

**Java Version?**
11.0.12

**OS Version?**
macOS Big Sur 11.5.2

**MySQL Version?**
mysql:mysql-connector-java version:8.0.24
aws-mysql-jdbc version: '0.2.0

**To Reproduce**
N/A

**Comment by hsuamz** [comment]
Hello @mealbarracin10,

Thanks for checking out the project! Currently, the project is under public preview and will be going through changes before we consider general availability for production use.

If you're evaluating the driver right now, we encourage all customers to use the latest release, which at this time is 0.2.0.

Let me know if you have any questions. As you're evaluating, if there is any feedback you want to share with us, we'd be happy to discuss.

Thanks,

Matthew

**Comment by hsuamz** [comment]
Hello @mealbarracin10,

The AWS JDBC Driver for MySQL is now generally available. You can refer to the latest release here: https://github.com/awslabs/aws-mysql-jdbc/releases/tag/1.0.0 and our updated README.md for updated information.

In addition, feel free to take a look at a blog post here: https://aws.amazon.com/blogs/database/improve-application-availability-with-the-aws-jdbc-driver-for-amazon-aurora-mysql/.

Thanks,

Matthew
